In [157]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

In [210]:
crime = pd.read_csv('crimes_against_women_2001-2014.csv')
# crime = crime.drop(['CRIME HEAD'],axis='columns')
crime.drop(['Year'],axis=1,inplace=True)
crime

Unnamed: 0        STATE/UT           DISTRICT  Rape  \
0               0  ANDHRA PRADESH           ADILABAD    50   
1               1  ANDHRA PRADESH          ANANTAPUR    23   
2               2  ANDHRA PRADESH           CHITTOOR    27   
3               3  ANDHRA PRADESH           CUDDAPAH    20   
4               4  ANDHRA PRADESH      EAST GODAVARI    23   
...           ...             ...                ...   ...   
10672         832     Lakshadweep        Lakshadweep     1   
10673         833     Lakshadweep  Total District(s)     1   
10674         834      Puducherry           Karaikal     3   
10675         835      Puducherry         Puducherry     7   
10676         836      Puducherry  Total District(s)    10   

       Kidnapping and Abduction  Dowry Deaths  \
0                            30            16   
1                            30             7   
2                            34            14   
3                            20            17   
4                            26            12   
...                         ...           ...   
10672                         0             0   
10673                         0             0   
10674                         1             0   
10675                         6             1   
10676                         7             1   

       Assault on women with intent to outrage her modesty  \
0                                                    149     
1                                                    118     
2                                                    112     
3                                                    126     
4                                                    109     
...                                                  ...     
10672                                                  1     
10673                                                  1     
10674                                                 12     
10675                                                 20     
10676                                                 32     

       Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                              34                                  175   
1                              24                                  154   
2                              83                                  186   
3                              38                                   57   
4                              58                                  247   
...                           ...                                  ...   
10672                           2                                    0   
10673                           2                                    0   
10674                           1                                    1   
10675                           7                                    3   
10676                           8                                    4   

       Importation of Girls  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  
...                     ...  
10672                     0  
10673                     0  
10674                     0  
10675                     0  
10676                     0  

[10677 rows x 10 columns]

In [211]:
crime.drop(['Unnamed: 0'],axis=1,inplace=True)
crime.drop(['DISTRICT'],axis=1,inplace=True)

In [212]:
print(crime['STATE/UT'].unique())
len(crime['STATE/UT'].unique())

['ANDHRA PRADESH' 'ARUNACHAL PRADESH' 'ASSAM' 'BIHAR' 'CHHATTISGARH' 'GOA'
 'GUJARAT' 'HARYANA' 'HIMACHAL PRADESH' 'JAMMU & KASHMIR' 'JHARKHAND'
 'KARNATAKA' 'KERALA' 'MADHYA PRADESH' 'MAHARASHTRA' 'MANIPUR' 'MEGHALAYA'
 'MIZORAM' 'NAGALAND' 'ODISHA' 'PUNJAB' 'RAJASTHAN' 'SIKKIM' 'TAMIL NADU'
 'TRIPURA' 'UTTAR PRADESH' 'UTTARAKHAND' 'WEST BENGAL' 'A & N ISLANDS'
 'CHANDIGARH' 'D & N HAVELI' 'DAMAN & DIU' 'DELHI' 'LAKSHADWEEP'
 'PUDUCHERRY' 'Andhra Pradesh' 'Arunachal Pradesh' 'Assam' 'Bihar'
 'Chhattisgarh' 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh'
 'Jammu & Kashmir' 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh'
 'Maharashtra' 'Manipur' 'Meghalaya' 'Mizoram' 'Nagaland' 'Odisha'
 'Punjab' 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Tripura' 'Uttar Pradesh'
 'Uttarakhand' 'West Bengal' 'A&N Islands' 'Chandigarh' 'D&N Haveli'
 'Daman & Diu' 'Delhi UT' 'Lakshadweep' 'Puducherry' 'Telangana'
 'A & N Islands']


72

In [215]:
def get_case_consistency(row):
    row = row['STATE/UT'].strip()
    row = row.upper()
    #row = row.title()
    return row
crime['STATE/UT'] = crime.apply(get_case_consistency, axis=1)
crime['STATE/UT'].replace("A&N ISLANDS", "A & N ISLANDS", inplace = True)
crime['STATE/UT'].replace("D&N HAVELI", "D & N HAVELI", inplace = True)
crime['STATE/UT'].replace("DELHI UT", "DELHI", inplace = True)
crime['STATE/UT'].unique()
crime

STATE/UT  Rape  Kidnapping and Abduction  Dowry Deaths  \
0      ANDHRA PRADESH    50                        30            16   
1      ANDHRA PRADESH    23                        30             7   
2      ANDHRA PRADESH    27                        34            14   
3      ANDHRA PRADESH    20                        20            17   
4      ANDHRA PRADESH    23                        26            12   
...               ...   ...                       ...           ...   
10672     LAKSHADWEEP     1                         0             0   
10673     LAKSHADWEEP     1                         0             0   
10674      PUDUCHERRY     3                         1             0   
10675      PUDUCHERRY     7                         6             1   
10676      PUDUCHERRY    10                         7             1   

       Assault on women with intent to outrage her modesty  \
0                                                    149     
1                                                    118     
2                                                    112     
3                                                    126     
4                                                    109     
...                                                  ...     
10672                                                  1     
10673                                                  1     
10674                                                 12     
10675                                                 20     
10676                                                 32     

       Insult to modesty of Women  Cruelty by Husband or his Relatives  \
0                              34                                  175   
1                              24                                  154   
2                              83                                  186   
3                              38                                   57   
4                              58                                  247   
...                           ...                                  ...   
10672                           2                                    0   
10673                           2                                    0   
10674                           1                                    1   
10675                           7                                    3   
10676                           8                                    4   

       Importation of Girls  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  
...                     ...  
10672                     0  
10673                     0  
10674                     0  
10675                     0  
10676                     0  

[10677 rows x 8 columns]

In [162]:

crime.isnull().sum()

STATE/UT                                               0
Rape                                                   0
Kidnapping and Abduction                               0
Dowry Deaths                                           0
Assault on women with intent to outrage her modesty    0
Insult to modesty of Women                             0
Cruelty by Husband or his Relatives                    0
Importation of Girls                                   0
dtype: int64

In [224]:
Year=[2001, 2002, 2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014], 
def func(total_case_all_years):

    for i in list(crime.columns)[1:]:
        total_case_all_years[i]=crime.groupby(['STATE/UT'])[i].sum()
        
    return total_case_all_years


total_case_all_years=pd.DataFrame()
total_case_all_years=func(total_case_all_years)
total_case_all_years.insert(0, 'Year', ["A & N ISLANDS","ANDHRA PRADESH","ARUNACHAL PRADESH","ASSAM","BIHAR","CHANDIGARH","CHHATTISGARH",
                                        "D & N HAVELI", "DAMAN & DIU","DELHI","GOA","GUJARAT","HARYANA",
                                        "HIMACHAL PRADESH","JAMMU & KASHMIR","JHARKHAND","KARNATAKA","KERALA", 
                                        "LAKSHADWEEP","MADHYA PRADESH","MAHARASHTRA","MANIPUR","MEGHALAYA",
                                        "MIZORAM","NAGALAND","ODISHA","PUDUCHERRY","PUNJAB","RAJASTHAN","SIKKIM",
                                        "TAMIL NADU","TELANGANA","TRIPURA","UTTAR PRADESH","UTTARAKHAND","WEST BENGAL"], True)
total_case_all_years['Total'] = total_case_all_years.iloc[:,[1,2,3,4,5,6,7]].sum(axis=1)
total_case_all_years

Year   Rape  Kidnapping and Abduction  \
STATE/UT                                                                
A & N ISLANDS          A & N ISLANDS    336                       212   
ANDHRA PRADESH        ANDHRA PRADESH  32150                     34504   
ARUNACHAL PRADESH  ARUNACHAL PRADESH   1316                      1470   
ASSAM                          ASSAM  40190                     62074   
BIHAR                          BIHAR  30758                     57086   
CHANDIGARH                CHANDIGARH    770                      1682   
CHHATTISGARH            CHHATTISGARH  29308                     11808   
D & N HAVELI            D & N HAVELI    132                       224   
DAMAN & DIU              DAMAN & DIU     60                        44   
DELHI                          DELHI  20312                     46586   
GOA                              GOA   1062                       640   
GUJARAT                      GUJARAT  11644                     34670   
HARYANA                      HARYANA  17110                     20016   
HIMACHAL PRADESH    HIMACHAL PRADESH   4674                      4116   
JAMMU & KASHMIR      JAMMU & KASHMIR   7038                     21164   
JHARKHAND                  JHARKHAND  22826                     14186   
KARNATAKA                  KARNATAKA  15056                     16262   
KERALA                        KERALA  20030                      4452   
LAKSHADWEEP              LAKSHADWEEP     20                         2   
MADHYA PRADESH        MADHYA PRADESH  90996                     35608   
MAHARASHTRA              MAHARASHTRA  48974                     30368   
MANIPUR                      MANIPUR   1068                      2606   
MEGHALAYA                  MEGHALAYA   2642                       670   
MIZORAM                      MIZORAM   2070                        30   
NAGALAND                    NAGALAND    562                       190   
ODISHA                        ODISHA  30480                     25588   
PUDUCHERRY                PUDUCHERRY    208                       306   
PUNJAB                        PUNJAB  14656                     15096   
RAJASTHAN                  RAJASTHAN  45684                     66278   
SIKKIM                        SIKKIM    570                       180   
TAMIL NADU                TAMIL NADU  16660                     30908   
TELANGANA                  TELANGANA   1958                      1422   
TRIPURA                      TRIPURA   5060                      2202   
UTTAR PRADESH          UTTAR PRADESH  51150                    135906   
UTTARAKHAND              UTTARAKHAND   3752                      6484   
WEST BENGAL              WEST BENGAL  47876                     61158   

                   Dowry Deaths  \
STATE/UT                          
A & N ISLANDS                20   
ANDHRA PRADESH            13844   
ARUNACHAL PRADESH             6   
ASSAM                      3268   
BIHAR                     32206   
CHANDIGARH                   90   
CHHATTISGARH               2758   
D & N HAVELI                  2   
DAMAN & DIU                   6   
DELHI                      3758   
GOA                          38   
GUJARAT                    1108   
HARYANA                    7372   
HIMACHAL PRADESH            112   
JAMMU & KASHMIR             294   
JHARKHAND                  7896   
KARNATAKA                  7016   
KERALA                      700   
LAKSHADWEEP                   0   
MADHYA PRADESH            21090   
MAHARASHTRA                9696   
MANIPUR                       6   
MEGHALAYA                    36   
MIZORAM                       8   
NAGALAND                      2   
ODISHA                    10782   
PUDUCHERRY                   56   
PUNJAB                     3524   
RAJASTHAN                 11854   
SIKKIM                        4   
TAMIL NADU                 5060   
TELANGANA                   578   
TRIPURA                     752   
UTTAR PRADESH             57256 

In [225]:
x = total_case_all_years.iloc[:,1].values
y = total_case_all_years.iloc[:,8].values
z=x*100/y
print(z)

[21.42857143  5.58786417 24.77409639 15.49559692 14.76081698 12.72306675
 24.75630564 23.32155477 26.08695652 13.34893074 25.75169738  5.2853758
 11.56675049 17.20026496  9.81699492 28.6830862   8.40366153  8.89526415
 37.03703704 19.48163721 11.40033148 19.11922664 48.83548983 48.07245704
 52.42537313 14.95627938  7.6526858  18.7277978   9.71615488 38.46153846
 10.23618177  7.72203818 16.0339692   8.78265379 12.70830511  8.89928175]


In [193]:
# import matplotlib.pyplot as plt
# fig = plt.figure()
# ax = fig.add_axes([0,0,1,1])
# x = total_case_all_years.iloc[:,1].values
# y = total_case_all_years.iloc[:,8].values
# ax.scatter(x,y)
# plt.show()

In [165]:
pd.DataFrame(total_case_all_years.sum(axis=1),columns=['Total Number of Cases'])

Total Number of Cases
STATE/UT                                
A & N ISLANDS                       3136
ANDHRA PRADESH                   1150674
ARUNACHAL PRADESH                  10624
ASSAM                             518706
BIHAR                             415848
CHANDIGARH                         12104
CHHATTISGARH                      236760
D & N HAVELI                        1132
DAMAN & DIU                          460
DELHI                             304322
GOA                                 8248
GUJARAT                           440612
HARYANA                           295844
HIMACHAL PRADESH                   54348
JAMMU & KASHMIR                   143384
JHARKHAND                         158862
KARNATAKA                         358226
KERALA                            450352
LAKSHADWEEP                          108
MADHYA PRADESH                    934038
MAHARASHTRA                       859162
MANIPUR                            11172
MEGHALAYA                          10812
MIZORAM                             8606
NAGALAND                            2142
ODISHA                            407552
PUDUCHERRY                          5436
PUNJAB                            156512
RAJASTHAN                         940358
SIKKIM                              2964
TAMIL NADU                        325482
TELANGANA                          50712
TRIPURA                            63116
UTTAR PRADESH                    1164790
UTTARAKHAND                        59046
WEST BENGAL                      1075698

In [204]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X = total_case_all_years.iloc[:,[1,2,3,4,5,6,7]].values
y = total_case_all_years.iloc[:,8].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
print(y)
regressor = LinearRegression()
regressor.fit(X_train,y_train)

print ("Your Test Set is:- \n",X_test)
#X_tst = np.array([2015, 0, 0,  0, 0, 0, 0, 0, 0, 0,  0, 0])
accuracy = regressor.score(X_test,y_test)
print("\nYour Prediction has the accuracy of-",accuracy*100,"%")

y_prediction = regressor.predict(X_test)
print("\nPredicted Total Crime for above given years is:-\n",y_prediction)

[  1568 575320   5312 259342 207472   6052 118374    566    230 152160
   4124 220306 147920  27174  71692  79282 179066 225176     54 466952
 429578   5586   5402   4300   1070 203758   2718  78254 470172   1482
 162726  25356  31558 582392  29522 537722]
Your Test Set is:- 
 [[ 30758  57086  32206  16958    694  69770    904]
 [  5060   2202    752   7344    114  16086      0]
 [    20      2      0     14      4     14      0]
 [ 32150  34504  13844 126952  86964 280906     34]
 [   562    190      2    260     24     32      2]
 [ 90996  35608  21090 195478  20964 102816    134]
 [  1316   1470      6   1996     48    476      0]
 [ 17110  20016   7372  17142  17866  68414      4]]

Your Prediction has the accuracy of- 100.0 %

Predicted Total Crime for above given years is:-
 [2.07472e+05 3.15580e+04 5.40000e+01 5.75320e+05 1.07000e+03 4.66952e+05
 5.31200e+03 1.47920e+05]
